server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud GateWay Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/members/**
            - Method=GET,PUT,DELETE
          filters:
            - AuthorizationHeaderFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
        - id: board-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/board-service/**
            - Method=PUT,DELETE
        - id: board-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/board-service/**
        - id: comment-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/comment-service/**
            - Method=PUT,DELETE
        - id: comment-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/comment-service/**